logging:
  config: classpath:logback-spring.xml
#  level:
#    org:
#      springframework: DEBUG
atp:
  devMode:
    peerName: peer
    ordererName: orderer
    peerUrl: grpc://10.176.40.68:7051
    ordererUrl: grpc://10.176.40.68:7050
    channelName: myc
#    baseUrl: http://47.94.164.138:8000 # 和华科对接

#    dpkiUrl: http://10.176.40.47/dpki  # 课题二(dpki)的
    couchdbUrl: http://10.176.40.68:5984

  path:
    dabeUser: atp/user/
    privateKey: atp/priKey/
    publicKey: atp/pubKey/
    cert: atp/cert/
    shareData: atp/data/
    encryptData: atp/data/enc/
    cipherData: atp/data/cipher/
    dbRecordData: atp/data/dbRecord/

  # TODO:注意，这个pattern如果修改，还要在EncryptContentCCRequest, DecryptContentCCRequest, ShareContentRequest里同时改！
  pattern:
    name: "[a-zA-Z0-9\u4e00-\u9fa5]+"
    attr: "[a-zA-Z0-9\u4e00-\u9f5a]+:[a-zA-Z0-9\u4e00-\u9fa5]+"



spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  datasource:
#    url: jdbc:mysql://192.168.3.78:3306/zdyf?serverTimezone=GMT&useSSL=false
    url: jdbc:mysql://10.176.40.68:3306/zdyf?serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /abe

#【br:暂时注释掉，下面3行】
#ipfs:
#  config:
#    multi-addr: /ip4/127.0.0.1/tcp/5001

