logging:
  config: classpath:logback-spring.xml
#  level:
#    org:
#      springframework: DEBUG
atp:
  devMode:
    peerName: peer
    ordererName: orderer
#    peerUrl: grpc://180.167.127.16:7051
#    ordererUrl: grpc://180.167.127.16:7050
    peerUrl: grpc://10.176.40.69:7051
    ordererUrl: grpc://10.176.40.69:7050
    channelName: myc
#    baseUrl: http://47.94.164.138:8000 # 和华科对接

#    dpkiUrl: http://10.176.40.47/dpki  # 课题二(dpki)的
    couchdbUrl: http://10.176.40.69:5984

  path:
    dabeUser: atp/user/
    privateKey: atp/priKey/
    publicKey: atp/pubKey/
    cert: atp/cert/
    shareData: atp/data/
    encryptData: atp/data/enc/
    cipherData: atp/data/cipher/

  # TODO:注意，这个pattern如果修改，还要在EncryptContentCCRequest, DecryptContentCCRequest, ShareContentRequest里同时改！
  pattern:
    name: "[a-zA-Z0-9\u4e00-\u9fa5]+"
    attr: "[a-zA-Z0-9\u4e00-\u9f5a]+:[a-zA-Z0-9\u4e00-\u9fa5]+"



spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

#  datasource:    # 我们zdyf的
#    url: jdbc:mysql://192.168.3.78:3306/zdyf?serverTimezone=GMT&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:   # 浦东项目的，改用gbase数据库
    # gbase驱动
    driver-class-name: org.postgresql.Driver
    # 15432 是gbase的默认端口
#    url: jdbc:postgresql://180.167.127.16:15432/postgres
    url: jdbc:postgresql://10.176.40.69:15432/postgres
    username: gaussdb
    password: Root@123

server:
  servlet:
    context-path: /abe


ipfs:
  config:


